server:
  image:
    repository: quay.io/prometheus/prometheus
    # if not set appVersion field from Chart.yaml is used
    tag: "v2.53.0"
    # When digest is set to a non-empty value, images will be pulled by digest (regardless of tag value).
